### PR TITLE
Example for fallback handler

### PR DESCRIPTION
**Pull request by ZaniaDeveloper**
Follows fixes for:
- kataras/iris#884 
- iris-contrib/middleware#32

### CODE REVIEW

**Comment by ZaniaDeveloper** [comment]
Travis failed cause in Iris project, [PR n°909](https://github.com/kataras/iris/pull/909) is not merged.

**Comment by ZaniaDeveloper** [comment]
Travis failed cause in Iris project, [PR n°909](https://github.com/kataras/iris/pull/909) is not merged.

**Comment by kataras** [comment]
@ZaniaDeveloper Can you push anothe PR to fix that? Thanks once again, for everyone else wants to read about the new feature @ZaniaDeveloper pushed to [Iris](https://iris-go.com), please navigate to the [github.com/kataras/iris PR:909](https://github.com/kataras/iris/pull/909).

err1

**Comment by ZaniaDeveloper** [comment]
I saw an error in fallback handler example, the function `fallbackHandler` is not used.

**Pull request merged**
